// lib/presentation/screens/admin/pet_edit_screen.dart
import 'package:flutter/material.dart';
import 'package:tugas_akhir/core/theme/app_colors.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';
import 'package:go_router/go_router.dart';
import 'package:tugas_akhir/core/models/user_model.dart';
import 'package:tugas_akhir/core/models/pet_model.dart';
import 'package:tugas_akhir/core/models/pet_medical_note_model.dart';
import 'package:tugas_akhir/presentation/screens/services/pet_service.dart';

class AdminEditPetScreen extends StatefulWidget {
  final PetModel pet;
  final UserModel customer;
  
  const AdminEditPetScreen({
    super.key,
    required this.pet,
    required this.customer,
  });

  @override
  State<AdminEditPetScreen> createState() => _AdminEditPetScreenState();
}

class _AdminEditPetScreenState extends State<AdminEditPetScreen> {
  final _formKey = GlobalKey<FormState>();
  final PetService _petService = PetService();
  final ImagePicker _picker = ImagePicker();

  // Data form
  late String _name;
  late String _type;
  late String _breed;
  late String _age;
  late String _weight;
  late bool _is_safe;
  
  // Medical notes
  String? _specialCondition;
  String? _currentMedication;
  String? _groomingBehavior;
  
  XFile? _selectedImage;
  File? _imageFile;
  String? _currentPhotoUrl;
  bool _isLoading = false;

  // List untuk dropdown
  final List<String> _petTypes = ['Kucing', 'Anjing', 'Kelinci', 'Hamster', 'Burung', 'Lainnya'];
  final Map<String, List<String>> _breedsByType = {
    'Kucing': ['Persia', 'Anggora', 'Siam', 'Domestik', 'British Shorthair', 'Maine Coon', 'Lainnya'],
    'Anjing': ['Golden Retriever', 'Poodle', 'Bulldog', 'Chihuahua', 'Husky', 'Beagle', 'Lainnya'],
    'Kelinci': ['Holland Lop', 'Netherland Dwarf', 'Flemish Giant', 'Lainnya'],
  };

  @override
  void initState() {
    super.initState();
    
    // Inisialisasi data dari widget.pet
    _name = widget.pet.name;
    _type = widget.pet.type;
    _breed = widget.pet.breed ?? '';
    _age = widget.pet.age ?? '';
    _weight = widget.pet.weight ?? '';
    
    _is_safe = widget.pet.is_safe == true || widget.pet.is_safe == '1';
    _currentPhotoUrl = widget.pet.photo;
    
    // Load medical notes
    _loadMedicalNotes();
  }

  Future<void> _loadMedicalNotes() async {
    try {
      final medicalNote = await _petService.getMedicalNoteByPetId(widget.pet.id);
      if (medicalNote != null) {
        setState(() {
          _specialCondition = medicalNote.special_condition;
          _currentMedication = medicalNote.current_medication;
          _groomingBehavior = medicalNote.grooming_behavior;
        });
      }
    } catch (e) {
      print('Error loading medical notes: $e');
    }
  }

  Future<void> _pickImage() async {
    final XFile? image = await _picker.pickImage(
      source: ImageSource.gallery,
      maxWidth: 800,
      maxHeight: 800,
      imageQuality: 85,
    );

    if (image != null) {
      setState(() {
        _selectedImage = image;
        _imageFile = File(image.path);
        _currentPhotoUrl = null;
      });
    }
  }

  Future<void> _takePhoto() async {
    final XFile? photo = await _picker.pickImage(
      source: ImageSource.camera,
      maxWidth: 800,
      maxHeight: 800,
      imageQuality: 85,
    );

    if (photo != null) {
      setState(() {
        _selectedImage = photo;
        _imageFile = File(photo.path);
        _currentPhotoUrl = null;
      });
    }
  }

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      
      setState(() => _isLoading = true);
      
      try {
        // Update pet data
        final updatedPet = widget.pet.copyWith(
          name: _name,
          type: _type,
          breed: _breed.isEmpty ? null : _breed,
          age: _age,
          weight: _weight,
          // is_safe: _isSafe,
        );
        
        // Save pet to database
        await _petService.updatePet(updatedPet);
        
        // Update or create medical notes
        final medicalNote = PetMedicalNoteModel(
          id: '', // Will be generated by database
          petId: widget.pet.id,
          special_condition: _specialCondition,
          current_medication: _currentMedication,
          grooming_behavior: _groomingBehavior,
          created_at: DateTime.now().toString(),
        );
        
        await _petService.saveMedicalNote(medicalNote);
        
        // Handle image upload if new image selected
        if (_selectedImage != null) {
          // TODO: Implement image upload to server
          // await _petService.uploadPetImage(_imageFile!, widget.pet.id);
        }
        
        // Show success message
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Hewan $_name berhasil diperbarui!'),
              backgroundColor: Colors.green,
              duration: const Duration(seconds: 2),
            ),
          );
          
          // Kembali ke halaman sebelumnya dengan data updated
          context.pop(updatedPet);
        }
      } catch (e) {
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Gagal memperbarui: $e'),
              backgroundColor: Colors.red,
              duration: const Duration(seconds: 2),
            ),
          );
        }
      } finally {
        setState(() => _isLoading = false);
      }
    }
  }

  void _showImageSourceDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Pilih Sumber Gambar'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.camera_alt),
              title: const Text('Ambil Foto'),
              onTap: () {
                context.pop();
                _takePhoto();
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: const Text('Pilih dari Galeri'),
              onTap: () {
                context.pop();
                _pickImage();
              },
            ),
            if (_currentPhotoUrl != null && _currentPhotoUrl!.startsWith('http'))
              ListTile(
                leading: const Icon(Icons.delete),
                title: const Text('Hapus Foto Saat Ini'),
                textColor: Colors.red,
                iconColor: Colors.red,
                onTap: () {
                  context.pop();
                  setState(() {
                    _currentPhotoUrl = null;
                    _selectedImage = null;
                    _imageFile = null;
                  });
                },
              ),
          ],
        ),
      ),
    );
  }

  void _showDeleteDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Hapus Hewan Peliharaan?'),
        content: Text(
          'Apakah Anda yakin ingin menghapus ${widget.pet.name} dari daftar peliharaan ${widget.customer.name}?\n\n'
          'Tindakan ini tidak dapat dibatalkan.',
        ),
        actions: [
          TextButton(
            onPressed: () => context.pop(),
            child: const Text('Batal'),
          ),
          ElevatedButton(
            onPressed: () async {
              context.pop();
              setState(() => _isLoading = true);
              
              try {
                await _petService.deletePet(widget.pet.id);
                
                if (context.mounted) {
                  // Kembali dengan status deleted
                  context.pop({'deleted': true, 'pet': widget.pet});
                  
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text('Hewan ${widget.pet.name} telah dihapus'),
                      backgroundColor: Colors.red,
                      duration: const Duration(seconds: 3),
                    ),
                  );
                }
              } catch (e) {
                if (context.mounted) {
                  ScaffoldMessenger.of(context).showSnackBar(
                    SnackBar(
                      content: Text('Gagal menghapus: $e'),
                      backgroundColor: Colors.red,
                    ),
                  );
                }
              } finally {
                setState(() => _isLoading = false);
              }
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
            ),
            child: const Text('Hapus'),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 2,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.black87),
          onPressed: () => context.pop(),
        ),
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Edit Hewan Peliharaan',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.black87,
              ),
            ),
            Text(
              widget.customer.name,
              style: TextStyle(
                fontSize: 12,
                color: Colors.grey[600],
              ),
            ),
          ],
        ),
        actions: [
          IconButton(
            icon: Icon(Icons.save, color: AppColors.orangeMedium),
            onPressed: _isLoading ? null : _submitForm,
            tooltip: 'Simpan',
          ),
          IconButton(
            icon: Icon(Icons.delete, color: Colors.red),
            onPressed: _isLoading ? null : _showDeleteDialog,
            tooltip: 'Hapus Hewan',
          ),
        ],
      ),
      body: _isLoading 
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Customer Info Banner
                    Card(
                      color: Colors.blue[50],
                      child: Padding(
                        padding: const EdgeInsets.all(12),
                        child: Row(
                          children: [
                            Icon(Icons.person, color: Colors.blue[700], size: 20),
                            const SizedBox(width: 8),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    'Pelanggan: ${widget.customer.name}',
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      color: Colors.blue[800],
                                    ),
                                  ),
                                  Text(
                                    'ID: ${widget.customer.id}',
                                    style: TextStyle(
                                      fontSize: 12,
                                      color: Colors.grey[600],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    
                    const SizedBox(height: 20),
                    
                    // Photo Section
                    Card(
                      child: Padding(
                        padding: const EdgeInsets.all(16),
                        child: Column(
                          children: [
                            Row(
                              children: [
                                Icon(Icons.photo_camera, size: 20, color: AppColors.orangeMedium),
                                const SizedBox(width: 8),
                                Text(
                                  'Foto Hewan',
                                  style: TextStyle(
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                    color: Colors.black87,
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                            GestureDetector(
                              onTap: _showImageSourceDialog,
                              child: Container(
                                width: 150,
                                height: 150,
                                decoration: BoxDecoration(
                                  color: Colors.grey[100],
                                  borderRadius: BorderRadius.circular(12),
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 2,
                                  ),
                                ),
                                child: _selectedImage != null
                                    ? ClipRRect(
                                        borderRadius: BorderRadius.circular(10),
                                        child: Image.file(
                                          _imageFile!,
                                          fit: BoxFit.cover,
                                        ),
                                      )
                                    : _currentPhotoUrl != null && _currentPhotoUrl!.startsWith('http')
                                        ? ClipRRect(
                                            borderRadius: BorderRadius.circular(10),
                                            child: Image.network(
                                              _currentPhotoUrl!,
                                              fit: BoxFit.cover,
                                              errorBuilder: (context, error, stackTrace) {
                                                return _buildPlaceholderImage();
                                              },
                                            ),
                                          )
                                        : _buildPlaceholderImage(),
                              ),
                            ),
                            const SizedBox(height: 8),
                            Text(
                              'Tap untuk mengubah foto',
                              style: TextStyle(
                                fontSize: 12,
                                color: Colors.grey[600],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    
                    const SizedBox(height: 20),
                    
                    // Basic Information Section
                    _buildSection(
                      title: 'Informasi Dasar',
                      icon: Icons.info,
                      children: [
                        // Nama Hewan
                        _buildAdminFormField(
                          label: 'Nama Hewan',
                          hintText: 'Masukkan nama hewan',
                          icon: Icons.pets,
                          initialValue: _name,
                          isRequired: true,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Nama hewan wajib diisi';
                            }
                            return null;
                          },
                          onSaved: (value) => _name = value!,
                        ),
                        const SizedBox(height: 16),
                        
                        // Jenis dan Ras
                        Row(
                          children: [
                            Expanded(
                              child: _buildAdminDropdown(
                                label: 'Jenis Hewan',
                                value: _type,
                                items: _petTypes,
                                icon: Icons.category,
                                onChanged: (value) {
                                  setState(() {
                                    _type = value!;
                                    if (_breedsByType[_type] != null && _breedsByType[_type]!.isNotEmpty) {
                                      _breed = _breedsByType[_type]!.first;
                                    }
                                  });
                                },
                              ),
                            ),
                            const SizedBox(width: 16),
                            Expanded(
                              child: _buildAdminDropdown(
                                label: 'Ras',
                                value: _breed,
                                items: _breedsByType[_type] ?? ['Tidak diketahui'],
                                icon: Icons.straighten,
                                onChanged: (value) {
                                  setState(() {
                                    _breed = value!;
                                  });
                                },
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 16),
                        
                        // Umur dan Berat
                        Row(
                          children: [
                            Expanded(
                              child: _buildAdminFormField(
                                label: 'Umur (tahun)',
                                hintText: '1',
                                icon: Icons.cake,
                                initialValue: _age.toString(),
                                keyboardType: TextInputType.number,
                                validator: (value) {
                                  if (value != null && value.isNotEmpty) {
                                    final age = int.tryParse(value);
                                    if (age == null || age <= 0) {
                                      return 'Umur harus angka positif';
                                    }
                                    if (age > 30) {
                                      return 'Umur tidak valid';
                                    }
                                  }
                                  return null;
                                },
                                onSaved: (value) => _age = value ?? ''
                              ),
                            ),
                            const SizedBox(width: 16),
                            Expanded(
                              child: _buildAdminFormField(
                                label: 'Berat (kg)',
                                hintText: '4.5',
                                icon: Icons.monitor_weight,
                                initialValue: _weight.toString(),
                                keyboardType: TextInputType.number,
                                validator: (value) {
                                  if (value != null && value.isNotEmpty) {
                                    final weight = double.tryParse(value);
                                    if (weight == null || weight <= 0) {
                                      return 'Berat harus angka positif';
                                    }
                                    if (weight > 100) {
                                      return 'Berat terlalu besar';
                                    }
                                  }
                                  return null;
                                },
                                onSaved: (value) => _weight = value ?? ''
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    
                    const SizedBox(height: 20),
                    
                    // Health Information Section
                    _buildSection(
                      title: 'Informasi Kesehatan',
                      icon: Icons.health_and_safety,
                      children: [
                        // Kondisi Khusus
                        _buildAdminFormField(
                          label: 'Kondisi Khusus',
                          hintText: 'Alergi, riwayat penyakit, dll.',
                          icon: Icons.medical_services,
                          initialValue: _specialCondition,
                          maxLines: 3,
                          onSaved: (value) => _specialCondition = value,
                        ),
                        const SizedBox(height: 16),
                        
                        // Obat yang Sedang Dikonsumsi
                        _buildAdminFormField(
                          label: 'Obat yang Sedang Dikonsumsi',
                          hintText: 'Nama obat, dosis, jadwal',
                          icon: Icons.medication,
                          initialValue: _currentMedication,
                          maxLines: 2,
                          onSaved: (value) => _currentMedication = value,
                        ),
                        const SizedBox(height: 16),
                        
                        // Perilaku Saat Grooming
                        _buildAdminFormField(
                          label: 'Perilaku Saat Grooming',
                          hintText: 'Takut air, agresif, dll.',
                          icon: Icons.psychology,
                          initialValue: _groomingBehavior,
                          maxLines: 2,
                          onSaved: (value) => _groomingBehavior = value,
                        ),
                        const SizedBox(height: 16),
                        
                        // Status Keamanan
                        Card(
                          color: _is_safe ? Colors.green[50] : Colors.orange[50],
                          child: Padding(
                            padding: const EdgeInsets.all(16),
                            child: Row(
                              children: [
                                Icon(
                                  _is_safe ? Icons.check_circle : Icons.warning,
                                  color: _is_safe ? Colors.green : Colors.orange,
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        'Status Keamanan',
                                        style: TextStyle(
                                          fontSize: 14,
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black87,
                                        ),
                                      ),
                                      Text(
                                        _is_safe == 'true'
                                            ? '✓ Aman untuk grooming reguler'
                                            : '⚠️ Memerlukan perhatian khusus',
                                        style: TextStyle(
                                          fontSize: 13,
                                          color: Colors.grey[700],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                Switch(
                                  value: _is_safe == 'true',
                                  activeColor: Colors.green,
                                  inactiveThumbColor: Colors.orange,
                                  onChanged: (value) {
                                    setState(() {
                                      _is_safe = value;
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                    
                    const SizedBox(height: 32),
                    
                    // Action Buttons
                    Row(
                      children: [
                        // Cancel Button
                        Expanded(
                          child: OutlinedButton(
                            onPressed: _isLoading ? null : () => context.pop(),
                            style: OutlinedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              side: BorderSide(color: Colors.grey[400]!),
                            ),
                            child: const Text('Batal'),
                          ),
                        ),
                        
                        const SizedBox(width: 16),
                        
                        // Save Button
                        Expanded(
                          child: ElevatedButton(
                            onPressed: _isLoading ? null : _submitForm,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.orangeMedium,
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(vertical: 16),
                            ),
                            child: _isLoading
                                ? const SizedBox(
                                    width: 20,
                                    height: 20,
                                    child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                                  )
                                : const Text('Simpan Perubahan'),
                          ),
                        ),
                      ],
                    ),
                    
                    const SizedBox(height: 20),
                  ],
                ),
              ),
            ),
    );
  }

  Widget _buildSection({
    required String title,
    required IconData icon,
    required List<Widget> children,
  }) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, size: 20, color: AppColors.orangeMedium),
                const SizedBox(width: 8),
                Text(
                  title,
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            ...children,
          ],
        ),
      ),
    );
  }

  Widget _buildAdminFormField({
    required String label,
    required String hintText,
    required IconData icon,
    String? initialValue,
    int? maxLines = 1,
    bool isRequired = false,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
    void Function(String?)? onSaved,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Text(
              label,
              style: TextStyle(
                fontWeight: FontWeight.w500,
                color: Colors.grey[700],
              ),
            ),
            if (isRequired) ...[
              const SizedBox(width: 4),
              Text(
                '*',
                style: TextStyle(
                  color: Colors.red[400],
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ],
        ),
        const SizedBox(height: 8),
        TextFormField(
          initialValue: initialValue,
          decoration: InputDecoration(
            hintText: hintText,
            prefixIcon: Icon(icon, color: AppColors.grey500),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: BorderSide(color: Colors.grey[300]!),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: BorderSide(color: Colors.grey[300]!),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: BorderSide(color: AppColors.orangeMedium),
            ),
            filled: true,
            fillColor: Colors.white,
          ),
          maxLines: maxLines,
          keyboardType: keyboardType,
          validator: validator,
          onSaved: onSaved,
        ),
      ],
    );
  }

  Widget _buildAdminDropdown({
    required String label,
    required String value,
    required List<String> items,
    required IconData icon,
    required void Function(String?)? onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: TextStyle(
            fontWeight: FontWeight.w500,
            color: Colors.grey[700],
          ),
        ),
        const SizedBox(height: 8),
        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: Colors.grey[300]!),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 8),
          child: Row(
            children: [
              Icon(icon, color: AppColors.grey500, size: 20),
              const SizedBox(width: 8),
              Expanded(
                child: DropdownButtonHideUnderline(
                  child: DropdownButton<String>(
                    value: value,
                    icon: const Icon(Icons.arrow_drop_down),
                    elevation: 16,
                    style: const TextStyle(color: Colors.black87, fontSize: 14),
                    isExpanded: true,
                    onChanged: onChanged,
                    items: items.map<DropdownMenuItem<String>>((String value) {
                      return DropdownMenuItem<String>(
                        value: value,
                        child: Text(value),
                      );
                    }).toList(),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildPlaceholderImage() {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        Icon(
          Icons.pets,
          size: 50,
          color: Colors.grey[300],
        ),
        const SizedBox(height: 8),
        Text(
          'Tidak ada foto',
          style: TextStyle(
            color: Colors.grey[500],
            fontSize: 12,
          ),
        ),
      ],
    );
  }
}
