// lib/presentation/screens/admin/pet_add_screen.dart
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:go_router/go_router.dart';
import 'package:tugas_akhir/core/theme/app_colors.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';
import 'package:tugas_akhir/core/models/user_model.dart';
import 'package:tugas_akhir/core/models/pet_model.dart';
import 'package:tugas_akhir/core/models/pet_medical_note_model.dart';
import 'package:tugas_akhir/presentation/screens/services/pet_service.dart';

class AdminAddPetScreen extends StatefulWidget {
  final UserModel customer;
  
  const AdminAddPetScreen({
    super.key,
    required this.customer,
  });

  @override
  State<AdminAddPetScreen> createState() => _AdminAddPetScreenState();
}

class _AdminAddPetScreenState extends State<AdminAddPetScreen> {
  final _formKey = GlobalKey<FormState>();
  final PetService _petService = PetService();
  final ImagePicker _picker = ImagePicker();

  // Data form
  String _name = '';
  String _type = 'Kucing';
  String _breed = '';
  String? _age;
  String? _weight;
  String? _specialCondition;
  String? _currentMedication;
  String? _groomingBehavior;
  String _isSafe = 'true';
  XFile? _selectedImage;
  bool _isLoading = false;

  // List untuk dropdown
  final List<String> _petTypes = ['Kucing', 'Anjing', 'Kelinci'];
  final Map<String, List<String>> _breedsByType = {
    'Kucing': ['Persia', 'Anggora', 'Siam', 'Domestik', 'British Shorthair', 'Maine Coon'],
    'Anjing': ['Golden Retriever', 'Poodle', 'Bulldog', 'Chihuahua', 'Husky', 'Beagle'],
    'Kelinci': ['Holland Lop', 'Netherland Dwarf', 'Flemish Giant'],
  };

  @override
  void initState() {
    super.initState();
    if (_breedsByType[_type] != null && _breedsByType[_type]!.isNotEmpty) {
      _breed = _breedsByType[_type]!.first;
    }
  }

  Future<void> _pickImage() async {
    final XFile? image = await _picker.pickImage(
      source: ImageSource.gallery,
      maxWidth: 800,
      maxHeight: 800,
      imageQuality: 85,
    );

    if (image != null) {
      setState(() {
        _selectedImage = image;
      });
    }
  }

  Future<void> _takePhoto() async {
    try {
      final XFile? photo = await _picker.pickImage(
        source: ImageSource.camera,
        maxWidth: 800,
        maxHeight: 800,
        imageQuality: 85,
      );
      if (photo != null) {
        setState(() {
          _selectedImage = photo;
        });
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Gagal mengambil foto: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  // ✅ FUNGSI UPLOAD FOTO KE 247GO
  Future<String?> _uploadPetImage(XFile imageFile, String petId) async {
    try {
      print('📤 Uploading image for pet: $petId');
      
      // Convert image to base64
      final bytes = await imageFile.readAsBytes();
      final base64Image = base64Encode(bytes);
      
      // API 247GO untuk upload image
      const String baseUrl = 'https://api.247go.app/v5/';
      const String token = '68f2ede325bcf6243d214a05';
      const String project = 'gugumicare';
      const String appId = '695d6cfd045a4b3d08976d16';
      
      final url = '${baseUrl}upload_image/token/$token/project/$project/collection/pet_photos/appid/$appId';
      
      final response = await http.post(
        Uri.parse(url),
        headers: {'Content-Type': 'application/x-www-form-urlencoded'},
        body: {
          'pet_id': petId,
          'image_name': 'pet_${DateTime.now().millisecondsSinceEpoch}.jpg',
          'image_data': base64Image,
        },
      );
      
      if (response.statusCode == 200) {
        final responseData = json.decode(response.body);
        if (responseData is Map && responseData.containsKey('image_url')) {
          final imageUrl = responseData['image_url'].toString();
          print('✅ Image uploaded successfully: $imageUrl');
          return imageUrl;
        }
      }
      
      print('❌ Failed to upload image: ${response.body}');
      return null;
    } catch (e) {
      print('💥 Error uploading image: $e');
      return null;
    }
  }

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();
      
      setState(() => _isLoading = true);
      
      try {
        // ✅ PERBAIKAN: Gunakan String untuk semua field
        final newPet = PetModel(
          id: '', // Will be generated by database
          user_id: widget.customer.id,
          name: _name,
          type: _type,
          breed: _breed.isEmpty ? null : _breed,
          age: _age,
          weight: _weight,
          is_safe: _isSafe,
          photo: null, // Akan diupdate setelah upload
          created_at: DateTime.now().toIso8601String(), // ✅ Convert to String
        );
        
        // Save pet to database
        final savedPet = await _petService.createPet(newPet);
        
        // ✅ UPLOAD FOTO JIKA ADA
        String? photoUrl;
        if (_selectedImage != null) {
          photoUrl = await _uploadPetImage(_selectedImage!, savedPet.id);
          
          // Update pet dengan URL foto
          if (photoUrl != null) {
            final updatedPet = savedPet.copyWith(photo: photoUrl);
            await _petService.updatePet(updatedPet);
          }
        }
        
        // Create medical notes
        final medicalNote = PetMedicalNoteModel(
          id: '', // Will be generated by database
          petId: savedPet.id,
          special_condition: _specialCondition,
          current_medication: _currentMedication,
          grooming_behavior: _groomingBehavior,
          created_at: DateTime.now().toIso8601String(),
        );            
        
        await _petService.saveMedicalNote(medicalNote);
        
        // Show success message
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Hewan $_name berhasil ditambahkan untuk ${widget.customer.name}!'),
              backgroundColor: Colors.green,
              duration: const Duration(seconds: 2),
            ),
          );
          
          // Kembali ke halaman detail customer dengan data baru
          context.pop(savedPet.copyWith(photo: photoUrl));
        }
      } catch (e) {
        if (context.mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Gagal menambahkan hewan: $e'),
              backgroundColor: Colors.red,
              duration: const Duration(seconds: 2),
            ),
          );
        }
      } finally {
        setState(() => _isLoading = false);
      }
    }
  }

  void _showImageSourceDialog() {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Pilih Sumber Gambar'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            ListTile(
              leading: const Icon(Icons.camera_alt),
              title: const Text('Ambil Foto'),
              onTap: () {
                Navigator.pop(context);
                _takePhoto();
              },
            ),
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: const Text('Pilih dari Galeri'),
              onTap: () {
                Navigator.pop(context);
                _pickImage();
              },
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 2,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.black87),
          onPressed: () => context.pop(),
        ),
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Tambah Hewan Baru',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.black87,
              ),
            ),
            Text(
              'Untuk: ${widget.customer.name}',
              style: TextStyle(
                fontSize: 12,
                color: Colors.grey[600],
              ),
            ),
          ],
        ),
        actions: [
          IconButton(
            onPressed: _isLoading ? null : _submitForm,
            icon: Icon(Icons.save, color: AppColors.orangeMedium),
            tooltip: 'Simpan',
          ),
        ],
      ),
      body: _isLoading 
          ? const Center(child: CircularProgressIndicator())
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Form(
                key: _formKey,
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Customer Info Banner
                    Card(
                      color: Colors.blue[50],
                      child: Padding(
                        padding: const EdgeInsets.all(12),
                        child: Row(
                          children: [
                            Icon(Icons.person, color: Colors.blue[700], size: 20),
                            const SizedBox(width: 8),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    'Pelanggan: ${widget.customer.name}',
                                    style: TextStyle(
                                      fontWeight: FontWeight.bold,
                                      color: Colors.blue[800],
                                    ),
                                  ),
                                  Text(
                                    'ID: ${widget.customer.id} • Email: ${widget.customer.email}',
                                    style: TextStyle(
                                      fontSize: 12,
                                      color: Colors.grey[600],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                    
                    const SizedBox(height: 20),
                    
                    // Photo Section
                    Card(
                      child: Padding(
                        padding: const EdgeInsets.all(16),
                        child: Column(
                          children: [
                            Row(
                              children: [
                                Icon(Icons.photo_camera, size: 20, color: AppColors.orangeMedium),
                                const SizedBox(width: 8),
                                Text(
                                  'Foto Hewan (Opsional)',
                                  style: TextStyle(
                                    fontSize: 16,
                                    fontWeight: FontWeight.bold,
                                    color: Colors.black87,
                                  ),
                                ),
                              ],
                            ),
                            const SizedBox(height: 16),
                            GestureDetector(
                              onTap: _showImageSourceDialog,
                              child: Container(
                                width: 150,
                                height: 150,
                                decoration: BoxDecoration(
                                  color: Colors.grey[100],
                                  borderRadius: BorderRadius.circular(12),
                                  border: Border.all(
                                    color: Colors.grey.shade300,
                                    width: 2,
                                  ),
                                ),
                                child: _selectedImage != null
                                    ? FutureBuilder<File?>(
                                        future: _selectedImage!.path.isNotEmpty 
                                            ? Future.value(File(_selectedImage!.path))
                                            : Future<File?>.value(null),
                                        builder: (context, snapshot) {
                                          if (snapshot.hasData && snapshot.data != null) {
                                            return ClipRRect(
                                              borderRadius: BorderRadius.circular(10),
                                              child: Image.file(
                                                snapshot.data!,
                                                fit: BoxFit.cover,
                                              ),
                                            );
                                          }
                                          return Column(
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            children: [
                                              Icon(
                                                Icons.pets,
                                                size: 50,
                                                color: Colors.grey[300],
                                              ),
                                              const SizedBox(height: 8),
                                              Text(
                                                'Tambahkan Foto',
                                                style: TextStyle(
                                                  color: Colors.grey[600],
                                                  fontSize: 12,
                                                ),
                                              ),
                                            ],
                                          );
                                        },
                                      )
                                    : Column(
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        children: [
                                          Icon(
                                            Icons.pets,
                                            size: 50,
                                            color: Colors.grey[300],
                                          ),
                                          const SizedBox(height: 8),
                                          Text(
                                            'Tambahkan Foto',
                                            style: TextStyle(
                                              color: Colors.grey[600],
                                              fontSize: 12,
                                            ),
                                          ),
                                        ],
                                      ),
                              ),
                            ),
                            if (_selectedImage != null) ...[
                              const SizedBox(height: 8),
                              Text(
                                _selectedImage!.name,
                                style: TextStyle(
                                  fontSize: 12,
                                  color: Colors.grey[600],
                                ),
                                overflow: TextOverflow.ellipsis,
                              ),
                            ],
                          ],
                        ),
                      ),
                    ),
                    
                    const SizedBox(height: 20),
                    
                    // Basic Information Section
                    _buildSection(
                      title: 'Informasi Dasar Hewan',
                      icon: Icons.info,
                      children: [
                        // Nama Hewan
                        _buildAdminFormField(
                          label: 'Nama Hewan',
                          hintText: 'Masukkan nama hewan',
                          icon: Icons.pets,
                          isRequired: true,
                          validator: (value) {
                            if (value == null || value.isEmpty) {
                              return 'Nama hewan wajib diisi';
                            }
                            return null;
                          },
                          onSaved: (value) => _name = value!,
                        ),
                        const SizedBox(height: 16),
                        
                        // Jenis dan Ras
                        Row(
                          children: [
                            Expanded(
                              child: _buildAdminDropdown(
                                label: 'Jenis Hewan',
                                value: _type,
                                items: _petTypes,
                                icon: Icons.category,
                                isRequired: true,
                                onChanged: (value) {
                                  setState(() {
                                    _type = value!;
                                    if (_breedsByType[_type] != null && _breedsByType[_type]!.isNotEmpty) {
                                      _breed = _breedsByType[_type]!.first;
                                    }
                                  });
                                },
                              ),
                            ),
                            const SizedBox(width: 16),
                            Expanded(
                              child: _buildAdminDropdown(
                                label: 'Ras',
                                value: _breed,
                                items: _breedsByType[_type] ?? ['Tidak diketahui'],
                                icon: Icons.straighten,
                                isRequired: true,
                                onChanged: (value) {
                                  setState(() {
                                    _breed = value!;
                                  });
                                },
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 16),
                        
                        // ✅ PERBAIKAN: Gunakan String untuk age dan weight
                        Row(
                          children: [
                            Expanded(
                              child: _buildAdminFormField(
                                label: 'Umur (tahun)',
                                hintText: '1',
                                icon: Icons.cake,
                                keyboardType: TextInputType.number,
                                validator: (value) {
                                  if (value != null && value.isNotEmpty) {
                                    final age = int.tryParse(value);
                                    if (age == null || age <= 0) {
                                      return 'Umur harus angka positif';
                                    }
                                    if (age > 30) {
                                      return 'Umur tidak valid';
                                    }
                                  }
                                  return null;
                                },
                                onSaved: (value) => _age = value,
                              ),
                            ),
                            const SizedBox(width: 16),
                            Expanded(
                              child: _buildAdminFormField(
                                label: 'Berat (kg)',
                                hintText: '4.5',
                                icon: Icons.monitor_weight,
                                keyboardType: TextInputType.number,
                                validator: (value) {
                                  if (value != null && value.isNotEmpty) {
                                    final weight = double.tryParse(value);
                                    if (weight == null || weight <= 0) {
                                      return 'Berat harus angka positif';
                                    }
                                    if (weight > 100) {
                                      return 'Berat terlalu besar';
                                    }
                                  }
                                  return null;
                                },
                                onSaved: (value) => _weight = value,
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    
                    const SizedBox(height: 20),
                    
                    // Health Information Section
                    _buildSection(
                      title: 'Informasi Kesehatan',
                      icon: Icons.medical_services,
                      children: [
                        // Kondisi Khusus
                        _buildAdminFormField(
                          label: 'Kondisi Khusus (Opsional)',
                          hintText: 'Alergi, riwayat penyakit, dll.',
                          icon: Icons.medical_information,
                          maxLines: 3,
                          onSaved: (value) => _specialCondition = value,
                        ),
                        const SizedBox(height: 16),
                        
                        // Obat yang Sedang Dikonsumsi
                        _buildAdminFormField(
                          label: 'Obat yang Sedang Dikonsumsi (Opsional)',
                          hintText: 'Nama obat, dosis, jadwal',
                          icon: Icons.medication,
                          maxLines: 2,
                          onSaved: (value) => _currentMedication = value,
                        ),
                        const SizedBox(height: 16),
                        
                        // Perilaku Saat Grooming
                        _buildAdminFormField(
                          label: 'Perilaku Saat Grooming (Opsional)',
                          hintText: 'Takut air, agresif, dll.',
                          icon: Icons.psychology,
                          maxLines: 2,
                          onSaved: (value) => _groomingBehavior = value,
                        ),
                        const SizedBox(height: 16),
                        
                        // Status Keamanan - ✅ PERBAIKAN: Gunakan String
                        Card(
                          color: (_isSafe == 'true') ? Colors.green[50] : Colors.orange[50],
                          child: Padding(
                            padding: const EdgeInsets.all(16),
                            child: Row(
                              children: [
                                Icon(
                                  (_isSafe == 'true') ? Icons.check_circle : Icons.warning,
                                  color: (_isSafe == 'true') ? Colors.green : Colors.orange,
                                ),
                                const SizedBox(width: 12),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Text(
                                        'Status Keamanan',
                                        style: TextStyle(
                                          fontSize: 14,
                                          fontWeight: FontWeight.bold,
                                          color: Colors.black87,
                                        ),
                                      ),
                                      Text(
                                        (_isSafe == 'true')
                                            ? '✓ Aman untuk grooming reguler'
                                            : '⚠️ Memerlukan perhatian khusus',
                                        style: TextStyle(
                                          fontSize: 13,
                                          color: Colors.grey[700],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                                Switch(
                                  value: _isSafe == 'true',
                                  activeColor: Colors.green,
                                  inactiveThumbColor: Colors.orange,
                                  onChanged: (value) {
                                    setState(() {
                                      _isSafe = value.toString();
                                    });
                                  },
                                ),
                              ],
                            ),
                          ),
                        ),
                      ],
                    ),
                    
                    const SizedBox(height: 32),
                    
                    // Action Buttons
                    Row(
                      children: [
                        // Cancel Button
                        Expanded(
                          child: OutlinedButton(
                            onPressed: _isLoading ? null : () => context.pop(),
                            style: OutlinedButton.styleFrom(
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              side: BorderSide(color: Colors.grey[400]!),
                            ),
                            child: const Text('Batal'),
                          ),
                        ),
                        
                        const SizedBox(width: 16),
                        
                        // Save Button
                        Expanded(
                          child: ElevatedButton(
                            onPressed: _isLoading ? null : _submitForm,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppColors.orangeMedium,
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(vertical: 16),
                            ),
                            child: _isLoading
                                ? const SizedBox(
                                    width: 20,
                                    height: 20,
                                    child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white),
                                  )
                                : const Text('Simpan Hewan'),
                          ),
                        ),
                      ],
                    ),
                    
                    const SizedBox(height: 20),
                    
                    // Admin Note
                    Container(
                      padding: const EdgeInsets.all(12),
                      decoration: BoxDecoration(
                        color: Colors.grey[50],
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(color: Colors.grey[300]!),
                      ),
                      child: Row(
                        children: [
                          Icon(Icons.info, size: 16, color: Colors.grey[600]),
                          const SizedBox(width: 8),
                          Expanded(
                            child: Text(
                              'Hewan ini akan ditambahkan ke profil ${widget.customer.name} dan dapat dilihat oleh customer',
                              style: TextStyle(
                                fontSize: 12,
                                color: Colors.grey[600],
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
            ),
    );
  }

  Widget _buildSection({
    required String title,
    required IconData icon,
    required List<Widget> children,
  }) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(icon, size: 20, color: AppColors.orangeMedium),
                const SizedBox(width: 8),
                Text(
                  title,
                  style: const TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 16),
            ...children,
          ],
        ),
      ),
    );
  }

  Widget _buildAdminFormField({
    required String label,
    required String hintText,
    required IconData icon,
    bool isRequired = false,
    int? maxLines = 1,
    TextInputType? keyboardType,
    String? Function(String?)? validator,
    void Function(String?)? onSaved,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Text(
              label,
              style: TextStyle(
                fontWeight: FontWeight.w500,
                color: Colors.grey[700],
              ),
            ),
            if (isRequired) ...[
              const SizedBox(width: 4),
              Text(
                '*',
                style: TextStyle(
                  color: Colors.red[400],
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ],
        ),
        const SizedBox(height: 8),
        TextFormField(
          decoration: InputDecoration(
            hintText: hintText,
            prefixIcon: Icon(icon, color: AppColors.grey500),
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: BorderSide(color: Colors.grey[300]!),
            ),
            enabledBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: BorderSide(color: Colors.grey[300]!),
            ),
            focusedBorder: OutlineInputBorder(
              borderRadius: BorderRadius.circular(8),
              borderSide: BorderSide(color: AppColors.orangeMedium),
            ),
            filled: true,
            fillColor: Colors.white,
          ),
          maxLines: maxLines,
          keyboardType: keyboardType,
          validator: validator,
          onSaved: onSaved,
        ),
      ],
    );
  }

  Widget _buildAdminDropdown({
    required String label,
    required String value,
    required List<String> items,
    required IconData icon,
    bool isRequired = false,
    required void Function(String?)? onChanged,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Text(
              label,
              style: TextStyle(
                fontWeight: FontWeight.w500,
                color: Colors.grey[700],
              ),
            ),
            if (isRequired) ...[
              const SizedBox(width: 4),
              Text(
                '*',
                style: TextStyle(
                  color: Colors.red[400],
                  fontWeight: FontWeight.bold,
                ),
              ),
            ],
          ],
        ),
        const SizedBox(height: 8),
        Container(
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(8),
            border: Border.all(color: Colors.grey[300]!),
          ),
          padding: const EdgeInsets.symmetric(horizontal: 8),
          child: Row(
            children: [
              Icon(icon, color: AppColors.grey500, size: 20),
              const SizedBox(width: 8),
              Expanded(
                child: DropdownButtonHideUnderline(
                  child: DropdownButton<String>(
                    value: value,
                    icon: const Icon(Icons.arrow_drop_down),
                    elevation: 16,
                    style: const TextStyle(color: Colors.black87, fontSize: 14),
                    isExpanded: true,
                    onChanged: onChanged,
                    items: items.map<DropdownMenuItem<String>>((String value) {
                      return DropdownMenuItem<String>(
                        value: value,
                        child: Text(value),
                      );
                    }).toList(),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
